### ISSUE TITLE
App Check and content security

### ISSUE THREAD

**Issue by davidreese** [Yeshivat-Torat-Shraga/YTS-App#29]
Need to verify app authenticity to allow access to firebase content

**Comment by benjitusk** [comment]
I connected the app to AppAttest on the [Firebase console](https://console.firebase.google.com/project/yeshivat-torat-shraga/settings/appcheck), but I'm not sure if I did it correctly, you may want to double check

**Comment by benjitusk** [comment]
@davidreese AppCheck is enabled and working on Simulator and real device. I set up the functions to log AppCheck info but to not reject the request if AppCheck is invalid, I'm waiting until you complete the search backend to enforce it. once that's done, we can close this issue.

**Comment by benjitusk** [comment]
As #68 is merged, I'm gonna mark this as closed
