### ISSUE TITLE
Fix App Fatal Error on slideshow Peek&Pop

### ISSUE THREAD

**Issue by benjitusk** [Yeshivat-Torat-Shraga/YTS-App#40]
stop timer on peek, restart on pop

**Comment by davidreese** [comment]
Context menu is also on the wrong object so it has a weird appearance

**Comment by benjitusk** [comment]
might remove context menu altogether, it's not a particularly useful one

> stop timer on peek, restart on pop

This is a lot harder than it sounds, too, might not be worth the effort

**Comment by benjitusk** [comment]
moot point, see 842cdfd
