### ISSUE TITLE
Error messages on launch screen

### ISSUE THREAD

**Issue by davidreese** [Yeshivat-Torat-Shraga/YTS-App#48]
Error messages for no internet connection and failed calls don't show on launch screen.

**Comment by benjitusk** [comment]
Prob the best way to approach this issue is by passing a closure to Home Model that will allow for showing alerts via the Root View

**Comment by benjitusk** [comment]
I think I'm gonna make an actual cover like the loading screen with a nice UI for the no internet error, with some nice graphics and a button to manually retry

**Comment by benjitusk** [comment]
closed by 2cdb2071f9bab026a5673ff7a71ef8e3307cf0d2
